services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cuidatedivirtiendote
    ports:
      - "3308:3306"
    volumes:
      - ./cuidatedivirtiendote.sql:/docker-entrypoint-initdb.d/cuidatedivirtiendote.sql

  pythonapp:
    build: ./cuidatedivirtiendote
    depends_on:
      - mysql
    ports:
      - "5001:5000"
    volumes:
      - ./cuidatedivirtiendote:/app
    environment:
      FLASK_ENV: production
